# Use root/example as user/password credentials
services:
  db:
    image: mariadb:10.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: SA
    ports:
      - "3307:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
